[package]
name = "parallax-hvm"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.12"
miette = { workspace = true }
thiserror = { workspace = true }

parallax-net = { path = "../parallax-net" }
parallax-resolve = { path = "../parallax-resolve" }
