[workspace]
members = [
    "crates/parallax-cli",
    "crates/parallax-ir",
    "crates/parallax-vm",
    "crates/parallax-lang",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
miette = { version = "7.4.0", features = ["fancy"] }
thiserror = "1.0"

[workspace.metadata]
default-run = "parallax-cli"
